repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code using rustfmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test-server
        name: cargo test (server)
        description: Run Rust tests (including server functionality)
        entry: cargo test --features server -- --test-threads 1
        language: system
        types: [rust]
        pass_filenames: false