repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code using rustfmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false